run:
	# to get links corresponding to responses generates response_links.txt, timeline_links.txt
	python3 T1_response.py
	python3 T1_timeline.py

	# now get data for the timelines
	python3 get_data_timeline.py

	#get data for responses
	python3 get_data_response.py

temp:
	python3 country_info.py