
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CONTENT ENDTABLE GARBAGE H2SPAN H3SPANstart : tableskiptag : content skiptag\n               | GARBAGE skiptag\n               | H2SPAN skiptag\n               | H3SPAN skiptag\n               | empty \n\n      handleh2span : H2SPAN CONTENT content \n                    | H2SPAN content\n                handleh4span : H3SPAN CONTENT contenthandledata : handleh2span handleh4span \n                | handleh2span \n                | handleh4span\n                        \n    handlehead :  handledata handlehead\n                  \n                  |\n    table : skiptag  BEGINTABLE content handlehead ENDTABLE skiptagempty :content : CONTENT content\n               | empty'
    
_lr_action_items = {'GARBAGE':([0,4,5,6,7,8,9,15,16,24,],[5,5,5,5,5,-18,-16,-17,-18,5,]),'H2SPAN':([0,4,5,6,7,8,9,10,15,16,17,19,20,21,22,24,26,27,28,29,31,32,],[6,6,6,6,6,-18,-16,-16,-17,-18,22,22,-11,-12,-16,6,-10,-16,-8,-16,-7,-9,]),'H3SPAN':([0,4,5,6,7,8,9,10,15,16,17,19,20,21,22,24,26,27,28,29,31,32,],[7,7,7,7,7,-18,-16,-16,-17,-18,23,23,23,-12,-16,7,-10,-16,-8,-16,-7,-9,]),'CONTENT':([0,4,5,6,7,8,9,10,15,16,22,23,24,27,29,],[9,9,9,9,9,-18,9,9,-17,-18,27,29,9,9,9,]),'BEGINTABLE':([0,3,4,5,6,7,8,9,11,12,13,14,15,16,],[-16,10,-16,-16,-16,-16,-6,-16,-2,-3,-4,-5,-17,-18,]),'$end':([1,2,4,5,6,7,8,9,11,12,13,14,15,16,24,30,],[0,-1,-16,-16,-16,-16,-6,-16,-2,-3,-4,-5,-17,-18,-16,-15,]),'ENDTABLE':([9,10,15,16,17,18,19,20,21,22,25,26,27,28,29,31,32,],[-16,-16,-17,-18,-14,24,-14,-11,-12,-16,-13,-10,-16,-8,-16,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([0,4,5,6,7,24,],[3,11,12,13,14,30,]),'content':([0,4,5,6,7,9,10,22,24,27,29,],[4,4,4,4,4,15,17,28,4,31,32,]),'empty':([0,4,5,6,7,9,10,22,24,27,29,],[8,8,8,8,8,16,16,16,8,16,16,]),'handlehead':([17,19,],[18,25,]),'handledata':([17,19,],[19,19,]),'handleh2span':([17,19,],[20,20,]),'handleh4span':([17,19,20,],[21,21,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','get_data_2020_response.py',58),
  ('skiptag -> content skiptag','skiptag',2,'p_skiptag','get_data_2020_response.py',62),
  ('skiptag -> GARBAGE skiptag','skiptag',2,'p_skiptag','get_data_2020_response.py',63),
  ('skiptag -> H2SPAN skiptag','skiptag',2,'p_skiptag','get_data_2020_response.py',64),
  ('skiptag -> H3SPAN skiptag','skiptag',2,'p_skiptag','get_data_2020_response.py',65),
  ('skiptag -> empty','skiptag',1,'p_skiptag','get_data_2020_response.py',66),
  ('handleh2span -> H2SPAN CONTENT content','handleh2span',3,'p_handleh2span','get_data_2020_response.py',74),
  ('handleh2span -> H2SPAN content','handleh2span',2,'p_handleh2span','get_data_2020_response.py',75),
  ('handleh4span -> H3SPAN CONTENT content','handleh4span',3,'p_handleh4span','get_data_2020_response.py',93),
  ('handledata -> handleh2span handleh4span','handledata',2,'p_handledata','get_data_2020_response.py',102),
  ('handledata -> handleh2span','handledata',1,'p_handledata','get_data_2020_response.py',103),
  ('handledata -> handleh4span','handledata',1,'p_handledata','get_data_2020_response.py',104),
  ('handlehead -> handledata handlehead','handlehead',2,'p_handlehead','get_data_2020_response.py',112),
  ('handlehead -> <empty>','handlehead',0,'p_handlehead','get_data_2020_response.py',114),
  ('table -> skiptag BEGINTABLE content handlehead ENDTABLE skiptag','table',6,'p_table','get_data_2020_response.py',121),
  ('empty -> <empty>','empty',0,'p_empty','get_data_2020_response.py',125),
  ('content -> CONTENT content','content',2,'p_content','get_data_2020_response.py',129),
  ('content -> empty','content',1,'p_content','get_data_2020_response.py',130),
]
