
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTIVE CATEGOR CLOSEBODY CLOSEDATA CLOSEDIV CLOSEHEAD CLOSEHEADER CLOSEHREF CLOSEROW CLOSETABLE CONTENT DEATHS LINE NEWCASES OPENBODY OPENDATA OPENDIV OPENHEAD OPENHEADER OPENHREF OPENROW OPENTABLE RECOVERED \n    start : active\n          | deaths\n          | newcases\n          | recover\n    \n    skipcontent : CONTENT skipcontent\n                | CONTENT \n    active : ACTIVE skipcontent CATEGOR CONTENT skipcontent LINE CONTENT\n    \n    deaths : DEATHS skipcontent CATEGOR CONTENT skipcontent LINE CONTENT\n    \n    newcases : NEWCASES skipcontent CATEGOR CONTENT skipcontent LINE CONTENT\n    \n    recover : RECOVERED skipcontent LINE CONTENT\n    '
    
_lr_action_items = {'ACTIVE':([0,],[6,]),'DEATHS':([0,],[7,]),'NEWCASES':([0,],[8,]),'RECOVERED':([0,],[9,]),'$end':([1,2,3,4,5,23,30,31,32,],[0,-1,-2,-3,-4,-10,-7,-8,-9,]),'CONTENT':([6,7,8,9,11,15,17,18,19,20,21,22,27,28,29,],[11,11,11,11,11,20,21,22,23,11,11,11,30,31,32,]),'CATEGOR':([10,11,12,13,16,],[15,-6,17,18,-5,]),'LINE':([11,14,16,24,25,26,],[-6,19,-5,27,28,29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'active':([0,],[2,]),'deaths':([0,],[3,]),'newcases':([0,],[4,]),'recover':([0,],[5,]),'skipcontent':([6,7,8,9,11,20,21,22,],[10,12,13,14,16,24,25,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> active','start',1,'p_start','module1_sub.py',120),
  ('start -> deaths','start',1,'p_start','module1_sub.py',121),
  ('start -> newcases','start',1,'p_start','module1_sub.py',122),
  ('start -> recover','start',1,'p_start','module1_sub.py',123),
  ('skipcontent -> CONTENT skipcontent','skipcontent',2,'p_skipcontent','module1_sub.py',128),
  ('skipcontent -> CONTENT','skipcontent',1,'p_skipcontent','module1_sub.py',129),
  ('active -> ACTIVE skipcontent CATEGOR CONTENT skipcontent LINE CONTENT','active',7,'p_active','module1_sub.py',133),
  ('deaths -> DEATHS skipcontent CATEGOR CONTENT skipcontent LINE CONTENT','deaths',7,'p_deaths','module1_sub.py',147),
  ('newcases -> NEWCASES skipcontent CATEGOR CONTENT skipcontent LINE CONTENT','newcases',7,'p_newcases','module1_sub.py',162),
  ('recover -> RECOVERED skipcontent LINE CONTENT','recover',4,'p_recover','module1_sub.py',176),
]
